import { type NextRequest, NextResponse } from "next/server"
import connectDB from "@/lib/db"
import User from "@/lib/models/User"

// Get users by role
export async function GET(request: NextRequest) {
  try {
    await connectDB()
    const { searchParams } = new URL(request.url)
    const role = searchParams.get("role")

    const query = role ? { role } : {}
    const users = await User.find(query)
      .select("_id customer_id email full_name role phone created_at")
      .sort({ created_at: -1 })

    // Convert to format expected by frontend
    const usersResponse = users.map((user) => ({
      user_id: user._id.toString(),
      customer_id: user.customer_id || null,
      email: user.email,
      full_name: user.full_name,
      role: user.role,
      phone: user.phone || "",
      created_at: user.created_at,
    }))

    return NextResponse.json({ users: usersResponse })
  } catch (error) {
    console.error("Get users error:", error)
    return NextResponse.json({ error: "Database error" }, { status: 500 })
  }
}

// Register new user
export async function POST(request: NextRequest) {
  try {
    // Connect to database
    await connectDB()
    console.log("✅ Database connected for registration")

    const { email, password, full_name, role, phone } = await request.json()

    // Validate required fields
    if (!email || !password || !full_name || !role) {
      return NextResponse.json(
        { error: "Missing required fields: email, password, full_name, and role are required" },
        { status: 400 }
      )
    }

    // Validate role
    if (!["customer", "employee"].includes(role)) {
      return NextResponse.json({ error: "Invalid role. Must be 'customer' or 'employee'" }, { status: 400 })
    }

    // Check if email already exists
    const existingUser = await User.findOne({ email })
    if (existingUser) {
      console.log("❌ Registration failed: Email already exists", email)
      return NextResponse.json({ error: "Email already registered" }, { status: 400 })
    }

    console.log("📝 Creating new user:", { email, role, full_name })

    // Create new user (customer_id will be auto-generated by pre-save hook)
    const newUser = new User({
      email,
      password,
      full_name,
      role,
      phone: phone || undefined,
    })

    await newUser.save()
    console.log("✅ User registered successfully:", {
      email: newUser.email,
      customer_id: newUser.customer_id,
      role: newUser.role,
    })

    return NextResponse.json({
      success: true,
      customer_id: newUser.customer_id,
      code: newUser.customer_id,
      message: role === "customer" ? "Customer registered successfully" : "Employee registered successfully",
    })
  } catch (error: any) {
    console.error("❌ Register user error:", error)
    console.error("Error details:", error.message, error.stack)
    
    // Provide more specific error messages
    if (error.code === 11000) {
      return NextResponse.json({ error: "Email already registered" }, { status: 400 })
    }
    
    return NextResponse.json(
      { error: error.message || "Failed to register user" },
      { status: 500 }
    )
  }
}
